//! Loads the CDP process catalog: the SoundThread-derived set (see
//! `scripts/convert_soundthread_catalog.py` and `THIRD_PARTY_NOTICES.md`), a hand-authored
//! extension set (`catalog_extra.toml` — processes SoundThread never covered, added directly
//! from CDP's own usage text; see `CDP-Ext-Plan.md`), and any user-authored definitions found
//! in `$XDG_CONFIG_HOME/tui-wave/cdp/*.toml`, in that order — each later source can override
//! an earlier one by reusing its `key`.

use std::path::{Path, PathBuf};

use serde::Deserialize;

use super::def::ProcessDef;

/// The SoundThread-derived catalog, generated by `scripts/convert_soundthread_catalog.py`
/// from SoundThread's `process_help.json` (MIT license — see `THIRD_PARTY_NOTICES.md`). Kept
/// separate from `catalog_extra.toml` (below) so this file can stay purely machine-generated,
/// matching its own "do not hand-edit" header.
const BUILTIN_CATALOG_TOML: &str = include_str!("catalog.toml");

/// Hand-authored process definitions for CDP programs SoundThread never covered (see
/// `CDP-Ext-Plan.md` for the inventory/rationale) — same `[[process]]` schema as the built-in
/// catalog and the user-extension directory, just bundled into the binary instead of read
/// from disk. Each entry's argv shape and parameter ranges are verified against the real
/// binary's own `--help`-style usage text (CDP programs print full usage with no arguments).
const EXTRA_CATALOG_TOML: &str = include_str!("catalog_extra.toml");

#[derive(Deserialize)]
struct CatalogFile {
    #[serde(default, rename = "process")]
    processes: Vec<ProcessDef>,
}

/// The full set of available CDP process definitions.
#[derive(Debug, Clone, Default)]
pub struct CdpCatalog {
    pub processes: Vec<ProcessDef>,
}

/// Parses `text` as a `[[process]]` catalog file and merges its entries into `by_key`: a
/// `key` matching an existing entry replaces it, a new `key` appends. Returns a warning
/// string (rather than erroring the whole catalog) on a parse failure, so one malformed
/// source never blocks every other one — the same "never block startup" philosophy as
/// `Config::load`.
fn merge_catalog_source(by_key: &mut Vec<ProcessDef>, text: &str, source: &str) -> Option<String> {
    match toml::from_str::<CatalogFile>(text) {
        Ok(parsed) => {
            for def in parsed.processes {
                if let Some(existing) = by_key.iter_mut().find(|p| p.key == def.key) {
                    *existing = def;
                } else {
                    by_key.push(def);
                }
            }
            None
        }
        Err(err) => Some(format!("{source}: {err}")),
    }
}

impl CdpCatalog {
    /// Parses the built-in catalog sources and merges in any `*.toml` files found in
    /// `user_dir` (when given), in source order — see this module's doc comment. Malformed
    /// sources are skipped, not fatal; their parse errors are returned as warnings for the
    /// caller to surface (e.g. in an Info dialog).
    pub fn load(user_dir: Option<&Path>) -> (Self, Vec<String>) {
        let mut warnings = Vec::new();
        let mut by_key: Vec<ProcessDef> = Vec::new();

        if let Some(w) = merge_catalog_source(&mut by_key, BUILTIN_CATALOG_TOML, "built-in CDP catalog") {
            warnings.push(w);
        }
        if let Some(w) = merge_catalog_source(&mut by_key, EXTRA_CATALOG_TOML, "built-in CDP extra catalog") {
            warnings.push(w);
        }

        if let Some(dir) = user_dir {
            let mut entries: Vec<PathBuf> = std::fs::read_dir(dir)
                .into_iter()
                .flatten()
                .filter_map(|e| e.ok())
                .map(|e| e.path())
                .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("toml"))
                .collect();
            // Deterministic merge order regardless of filesystem iteration order.
            entries.sort();

            for path in entries {
                let text = match std::fs::read_to_string(&path) {
                    Ok(text) => text,
                    Err(err) => {
                        warnings.push(format!("{}: {err}", path.display()));
                        continue;
                    }
                };
                if let Some(w) = merge_catalog_source(&mut by_key, &text, &path.display().to_string()) {
                    warnings.push(w);
                }
            }
        }

        (Self { processes: by_key }, warnings)
    }

    /// The directory user-authored CDP process definitions are read from:
    /// `$XDG_CONFIG_HOME/tui-wave/cdp/` (falling back to `$HOME/.config/tui-wave/cdp/`).
    /// Returned unconditionally — callers pass it to `load` regardless of whether it
    /// exists (`load` treats a missing directory as "no user definitions", not an error).
    pub fn user_dir() -> PathBuf {
        let config_home = std::env::var("XDG_CONFIG_HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|_| {
                let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
                PathBuf::from(home).join(".config")
            });
        config_home.join("tui-wave").join("cdp")
    }

    /// Looks up a process by its stable key. Test-only: production code always already has
    /// a `catalog_index` in hand (from the browser's filtered `entries` list) and indexes
    /// `processes` directly rather than searching by key; tests use this to grab a specific
    /// named process (e.g. `"blur_avrg"`) without hardcoding its index.
    #[cfg(test)]
    pub fn find(&self, key: &str) -> Option<&ProcessDef> {
        self.processes.iter().find(|p| p.key == key)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_catalog_parses() {
        let (catalog, warnings) = CdpCatalog::load(None);
        assert!(warnings.is_empty(), "unexpected warnings: {warnings:?}");
        assert!(
            !catalog.processes.is_empty(),
            "expected the built-in catalog to contain process definitions"
        );
    }

    #[test]
    fn builtin_keys_are_unique() {
        let (catalog, _) = CdpCatalog::load(None);
        let mut keys: Vec<&str> = catalog.processes.iter().map(|p| p.key.as_str()).collect();
        let count_before = keys.len();
        keys.sort_unstable();
        keys.dedup();
        assert_eq!(keys.len(), count_before, "duplicate process keys in built-in catalog");
    }

    /// Checks one `TableColumn`-shaped bounds set (used directly by `Table` columns, and
    /// reused for each of `HiliteBand`'s five numeric fields).
    fn assert_column_sane(proc_key: &str, param_name: &str, col: &super::super::def::TableColumn) {
        assert!(
            col.min <= col.max,
            "{proc_key}: param {param_name:?} column {:?} has min {} > max {}",
            col.name,
            col.min,
            col.max
        );
        assert!(
            col.default >= col.min && col.default <= col.max,
            "{proc_key}: param {param_name:?} column {:?} default {} out of range [{}, {}]",
            col.name,
            col.default,
            col.min,
            col.max
        );
    }

    #[test]
    fn builtin_number_params_have_sane_ranges() {
        use super::super::def::ParamKind;
        let (catalog, _) = CdpCatalog::load(None);
        for proc in &catalog.processes {
            for param in &proc.params {
                match &param.kind {
                    ParamKind::Number { min, max, default, .. } => {
                        assert!(
                            *min <= *max,
                            "{}: param {:?} has min {min} > max {max}",
                            proc.key,
                            param.name
                        );
                        assert!(
                            *default >= *min && *default <= *max,
                            "{}: param {:?} default {default} out of range [{min}, {max}]",
                            proc.key,
                            param.name
                        );
                    }
                    ParamKind::Table { columns, .. } => {
                        for col in columns {
                            assert_column_sane(&proc.key, &param.name, col);
                        }
                    }
                    ParamKind::MarkerTimeList { min, max, default, markers, .. } => {
                        assert!(
                            *min <= *max,
                            "{}: param {:?} has min {min} > max {max}",
                            proc.key,
                            param.name
                        );
                        assert!(
                            *default >= *min && *default <= *max,
                            "{}: param {:?} default {default} out of range [{min}, {max}]",
                            proc.key,
                            param.name
                        );
                        assert!(
                            !markers.is_empty(),
                            "{}: param {:?} declares no marker characters at all",
                            proc.key,
                            param.name
                        );
                    }
                    ParamKind::HiliteBand { lofrq, hifrq, amp1, amp2, transpose } => {
                        for col in [lofrq, hifrq, amp1, amp2, transpose] {
                            assert_column_sane(&proc.key, &param.name, col);
                        }
                    }
                    ParamKind::Toggle { .. } | ParamKind::Choice { .. } | ParamKind::FormantBufferRef { .. } => {}
                }
            }
        }
    }

    /// Every process's title must reveal which CDP binary it came from (e.g. "Blur
    /// Average", "Hilite Band") — the browser's Groups column filters by `subcategory` (a
    /// semantic category like "spectrum"), not by binary, so without this the process's CDP
    /// family is invisible anywhere in the UI (user report, 2026-07-14). Checked
    /// space-insensitively (title with spaces removed must contain the bin name) since a
    /// title can legitimately spell a compound bin name as separate words, e.g. tapdelay's
    /// "Tap Delay". The handful of processes literally titled after their own bin (e.g.
    /// blur's own "Blur" entry) trivially satisfy this too, so there's no exclusion list to
    /// maintain — this only ever needs updating if a new hand-authored entry's title
    /// forgets the bin name.
    #[test]
    fn builtin_titles_reveal_their_own_cdp_binary() {
        let (catalog, _) = CdpCatalog::load(None);
        for proc in &catalog.processes {
            let squashed_title = proc.title.to_lowercase().replace(' ', "");
            let bin_lower = proc.bin.to_lowercase();
            assert!(
                squashed_title.contains(&bin_lower),
                "{}: title {:?} doesn't reveal its own CDP binary {:?}",
                proc.key,
                proc.title,
                proc.bin
            );
        }
    }

    /// A `required_list`/`required_envelope` field is unreachable in the UI unless
    /// `automatable` is also true — `App::open_cdp_list_editor`/`open_cdp_envelope_editor`
    /// both gate on `param.automatable` before opening (reusing the existing 'e'-key gate
    /// meant for optional breakpoint automation on a plain constant). Found via manual
    /// testing (2026-07-13): several freshly-authored `required_list` fields
    /// (`synth chord`'s pitch/frequency list, `pitch tune`'s template, `pitch chord`/
    /// `chordf`'s transposition list) had `automatable = false`, silently making the field's
    /// only editor unreachable — pressing 'e' did nothing, with no error. The smoke test
    /// can't catch this class of bug at all (it constructs `ParamValue`s directly, bypassing
    /// the UI's key handling entirely), so this is a static catalog-data check instead.
    #[test]
    fn builtin_required_datafile_params_are_automatable() {
        let (catalog, _) = CdpCatalog::load(None);
        for proc in &catalog.processes {
            for param in &proc.params {
                if param.required_list || param.required_envelope {
                    assert!(
                        param.automatable,
                        "{}: param {:?} is required_list/required_envelope but not \
                         automatable -- its 'e'-key editor would be unreachable",
                        proc.key,
                        param.name
                    );
                }
            }
        }
    }

    /// An enabled toggle's entire argv contribution IS its flag token (`pipeline.rs`
    /// emits nothing for a flagless toggle rather than an empty token) — so a toggle
    /// param without a flag can never reach CDP at all, silently. A bare-word toggle is
    /// already expressible as `flag = "word"`; there is no valid reason for `flag` to be
    /// absent or empty on a toggle.
    #[test]
    fn builtin_toggle_params_always_carry_a_flag() {
        use super::super::def::ParamKind;
        let (catalog, _) = CdpCatalog::load(None);
        for proc in &catalog.processes {
            for param in &proc.params {
                if matches!(param.kind, ParamKind::Toggle { .. }) {
                    assert!(
                        param.flag.as_deref().is_some_and(|f| !f.is_empty()),
                        "{}: toggle param {:?} has no flag -- enabling it would emit nothing",
                        proc.key,
                        param.name
                    );
                }
            }
        }
    }

    #[test]
    fn user_dir_override_replaces_and_append_adds() {
        let dir = std::env::temp_dir().join(format!(
            "tui-wave-cdp-catalog-test-{}",
            std::process::id()
        ));
        std::fs::create_dir_all(&dir).unwrap();

        let (builtin, _) = CdpCatalog::load(None);
        let existing_key = builtin.processes[0].key.clone();

        let override_toml = format!(
            r#"
[[process]]
key = "{existing_key}"
bin = "blur"
subprog = "avrg"
title = "Overridden Title"
category = "time"
subcategory = "distort"
short_description = "overridden"
description = "overridden"
input = "wav"
output = "wav"
stereo_native = false
output_is_stereo = false
params = []

[[process]]
key = "my_custom_process"
bin = "modify"
subprog = "speed"
mode = "2"
title = "Custom"
category = "time"
subcategory = "pitch"
short_description = "custom"
description = "custom"
input = "wav"
output = "wav"
stereo_native = true
output_is_stereo = true
params = []
"#
        );
        std::fs::write(dir.join("extra.toml"), override_toml).unwrap();

        let (merged, warnings) = CdpCatalog::load(Some(&dir));
        assert!(warnings.is_empty(), "unexpected warnings: {warnings:?}");
        assert_eq!(merged.processes.len(), builtin.processes.len() + 1);
        assert_eq!(merged.find(&existing_key).unwrap().title, "Overridden Title");
        assert!(merged.find("my_custom_process").is_some());

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn malformed_user_file_produces_warning_not_panic() {
        let dir = std::env::temp_dir().join(format!(
            "tui-wave-cdp-catalog-badtest-{}",
            std::process::id()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("broken.toml"), "this is not [ valid toml").unwrap();

        let (merged, warnings) = CdpCatalog::load(Some(&dir));
        assert!(!warnings.is_empty());
        // Built-ins still loaded despite the broken user file.
        assert!(!merged.processes.is_empty());

        std::fs::remove_dir_all(&dir).ok();
    }

    /// The documented example custom-process file (`docs/cdp-custom-process-example.toml`,
    /// referenced from USERGUIDE.md) must always load cleanly through the same path a real
    /// user directory uses — otherwise the docs would ship an example that doesn't work.
    #[test]
    fn shipped_example_custom_process_loads() {
        let example = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("docs")
            .join("cdp-custom-process-example.toml");
        assert!(example.is_file(), "example file missing: {}", example.display());

        let dir = std::env::temp_dir().join(format!(
            "tui-wave-cdp-example-test-{}",
            std::process::id()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::copy(&example, dir.join("example.toml")).unwrap();

        let (merged, warnings) = CdpCatalog::load(Some(&dir));
        assert!(warnings.is_empty(), "example file produced warnings: {warnings:?}");
        let def = merged.find("modify_speed_1").expect("example process should load");
        assert_eq!(def.bin, "modify");
        assert_eq!(def.params.len(), 1);

        std::fs::remove_dir_all(&dir).ok();
    }
}
