//! Loads the CDP process catalog: the built-in set (ported from SoundThread, see
//! `scripts/convert_soundthread_catalog.py` and `THIRD_PARTY_NOTICES.md`) merged with any
//! user-authored definitions found in `$XDG_CONFIG_HOME/tui-wave/cdp/*.toml`.

use std::path::{Path, PathBuf};

use serde::Deserialize;

use super::def::ProcessDef;

/// The built-in catalog, generated by `scripts/convert_soundthread_catalog.py` from
/// SoundThread's `process_help.json` (MIT license — see `THIRD_PARTY_NOTICES.md`).
const BUILTIN_CATALOG_TOML: &str = include_str!("catalog.toml");

#[derive(Deserialize)]
struct CatalogFile {
    #[serde(default, rename = "process")]
    processes: Vec<ProcessDef>,
}

/// The full set of available CDP process definitions.
#[derive(Debug, Clone, Default)]
pub struct CdpCatalog {
    pub processes: Vec<ProcessDef>,
}

impl CdpCatalog {
    /// Parses the built-in catalog and merges in any `*.toml` files found in `user_dir`
    /// (when given). A user file with the same `key` as a built-in entry replaces it; a new
    /// key appends. Malformed user files are skipped, not fatal — their parse errors are
    /// returned as warnings for the caller to surface (e.g. in an Info dialog), matching
    /// `Config::load`'s "never block startup" philosophy.
    pub fn load(user_dir: Option<&Path>) -> (Self, Vec<String>) {
        let mut warnings = Vec::new();

        let builtin: CatalogFile = match toml::from_str(BUILTIN_CATALOG_TOML) {
            Ok(catalog) => catalog,
            Err(err) => {
                // The built-in catalog is generated and committed; a parse failure here is
                // a packaging bug, not a user-facing runtime condition, but must still not
                // crash the app.
                warnings.push(format!("built-in CDP catalog failed to parse: {err}"));
                CatalogFile { processes: Vec::new() }
            }
        };

        let mut by_key: Vec<ProcessDef> = builtin.processes;

        if let Some(dir) = user_dir {
            let mut entries: Vec<PathBuf> = std::fs::read_dir(dir)
                .into_iter()
                .flatten()
                .filter_map(|e| e.ok())
                .map(|e| e.path())
                .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("toml"))
                .collect();
            // Deterministic merge order regardless of filesystem iteration order.
            entries.sort();

            for path in entries {
                let text = match std::fs::read_to_string(&path) {
                    Ok(text) => text,
                    Err(err) => {
                        warnings.push(format!("{}: {err}", path.display()));
                        continue;
                    }
                };
                let parsed: CatalogFile = match toml::from_str(&text) {
                    Ok(parsed) => parsed,
                    Err(err) => {
                        warnings.push(format!("{}: {err}", path.display()));
                        continue;
                    }
                };
                for def in parsed.processes {
                    if let Some(existing) = by_key.iter_mut().find(|p| p.key == def.key) {
                        *existing = def;
                    } else {
                        by_key.push(def);
                    }
                }
            }
        }

        (Self { processes: by_key }, warnings)
    }

    /// The directory user-authored CDP process definitions are read from:
    /// `$XDG_CONFIG_HOME/tui-wave/cdp/` (falling back to `$HOME/.config/tui-wave/cdp/`).
    /// Returned unconditionally — callers pass it to `load` regardless of whether it
    /// exists (`load` treats a missing directory as "no user definitions", not an error).
    pub fn user_dir() -> PathBuf {
        let config_home = std::env::var("XDG_CONFIG_HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|_| {
                let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
                PathBuf::from(home).join(".config")
            });
        config_home.join("tui-wave").join("cdp")
    }

    /// Looks up a process by its stable key. Test-only: production code always already has
    /// a `catalog_index` in hand (from the browser's filtered `entries` list) and indexes
    /// `processes` directly rather than searching by key; tests use this to grab a specific
    /// named process (e.g. `"blur_avrg"`) without hardcoding its index.
    #[cfg(test)]
    pub fn find(&self, key: &str) -> Option<&ProcessDef> {
        self.processes.iter().find(|p| p.key == key)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_catalog_parses() {
        let (catalog, warnings) = CdpCatalog::load(None);
        assert!(warnings.is_empty(), "unexpected warnings: {warnings:?}");
        assert!(
            !catalog.processes.is_empty(),
            "expected the built-in catalog to contain process definitions"
        );
    }

    #[test]
    fn builtin_keys_are_unique() {
        let (catalog, _) = CdpCatalog::load(None);
        let mut keys: Vec<&str> = catalog.processes.iter().map(|p| p.key.as_str()).collect();
        let count_before = keys.len();
        keys.sort_unstable();
        keys.dedup();
        assert_eq!(keys.len(), count_before, "duplicate process keys in built-in catalog");
    }

    #[test]
    fn builtin_number_params_have_sane_ranges() {
        use super::super::def::ParamKind;
        let (catalog, _) = CdpCatalog::load(None);
        for proc in &catalog.processes {
            for param in &proc.params {
                if let ParamKind::Number { min, max, default, .. } = param.kind {
                    assert!(
                        min <= max,
                        "{}: param {:?} has min {min} > max {max}",
                        proc.key,
                        param.name
                    );
                    assert!(
                        default >= min && default <= max,
                        "{}: param {:?} default {default} out of range [{min}, {max}]",
                        proc.key,
                        param.name
                    );
                }
            }
        }
    }

    #[test]
    fn user_dir_override_replaces_and_append_adds() {
        let dir = std::env::temp_dir().join(format!(
            "tui-wave-cdp-catalog-test-{}",
            std::process::id()
        ));
        std::fs::create_dir_all(&dir).unwrap();

        let (builtin, _) = CdpCatalog::load(None);
        let existing_key = builtin.processes[0].key.clone();

        let override_toml = format!(
            r#"
[[process]]
key = "{existing_key}"
bin = "blur"
subprog = "avrg"
title = "Overridden Title"
category = "time"
subcategory = "distort"
short_description = "overridden"
description = "overridden"
input = "wav"
output = "wav"
stereo_native = false
output_is_stereo = false
params = []

[[process]]
key = "my_custom_process"
bin = "modify"
subprog = "speed"
mode = "2"
title = "Custom"
category = "time"
subcategory = "pitch"
short_description = "custom"
description = "custom"
input = "wav"
output = "wav"
stereo_native = true
output_is_stereo = true
params = []
"#
        );
        std::fs::write(dir.join("extra.toml"), override_toml).unwrap();

        let (merged, warnings) = CdpCatalog::load(Some(&dir));
        assert!(warnings.is_empty(), "unexpected warnings: {warnings:?}");
        assert_eq!(merged.processes.len(), builtin.processes.len() + 1);
        assert_eq!(merged.find(&existing_key).unwrap().title, "Overridden Title");
        assert!(merged.find("my_custom_process").is_some());

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn malformed_user_file_produces_warning_not_panic() {
        let dir = std::env::temp_dir().join(format!(
            "tui-wave-cdp-catalog-badtest-{}",
            std::process::id()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("broken.toml"), "this is not [ valid toml").unwrap();

        let (merged, warnings) = CdpCatalog::load(Some(&dir));
        assert!(!warnings.is_empty());
        // Built-ins still loaded despite the broken user file.
        assert!(!merged.processes.is_empty());

        std::fs::remove_dir_all(&dir).ok();
    }

    /// The documented example custom-process file (`docs/cdp-custom-process-example.toml`,
    /// referenced from USERGUIDE.md) must always load cleanly through the same path a real
    /// user directory uses — otherwise the docs would ship an example that doesn't work.
    #[test]
    fn shipped_example_custom_process_loads() {
        let example = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("docs")
            .join("cdp-custom-process-example.toml");
        assert!(example.is_file(), "example file missing: {}", example.display());

        let dir = std::env::temp_dir().join(format!(
            "tui-wave-cdp-example-test-{}",
            std::process::id()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::copy(&example, dir.join("example.toml")).unwrap();

        let (merged, warnings) = CdpCatalog::load(Some(&dir));
        assert!(warnings.is_empty(), "example file produced warnings: {warnings:?}");
        let def = merged.find("modify_speed_1").expect("example process should load");
        assert_eq!(def.bin, "modify");
        assert_eq!(def.params.len(), 1);

        std::fs::remove_dir_all(&dir).ok();
    }
}
