//! CDP's own process grouping, derived from a process's binary rather than stored per entry.
//!
//! The group names and their membership are taken directly from CDP's two index pages —
//! `cgroundx.htm` (time domain) and `cspecndx.htm` (spectral) — so a group heading here reads
//! exactly as it does in CDP's documentation, its printed manuals, and the CDP GUI. That is the
//! whole point of grouping this way: someone reading CDP's own material about `blur scatter`
//! finds it under BLUR here too, with no translation step.
//!
//! This replaced a hand-assigned `ProcessDef.subcategory` taxonomy that grouped by *sonic
//! function* instead (`distort`, `texture`, `filter`, `envelope`, …). That scheme read better to
//! a newcomer, but it had two costs that decided the switch: it disagreed with every piece of
//! CDP documentation a user might consult, and its buckets were badly lopsided (`texture` alone
//! held 82 of 407 processes while `amplitude` and `channels` held one each). Note the CDP
//! scheme does not fully fix lopsidedness — DISTORT is 83 processes — but that bucket is at
//! least coherent and is what CDP itself calls it.
//!
//! **Derived, never stored.** The mapping is a pure function of `bin` (plus `category`, for the
//! two binaries that exist in both domains), so it needs no new catalog field. That matters
//! because `catalog.toml` is machine-generated by `scripts/convert_soundthread_catalog.py` and
//! carries a "do not hand-edit" header — a per-entry group column would be silently reverted by
//! the next converter run, and 407 hand-edits would be unreviewable besides. A table here is
//! also the only place a CDP docs correction has to land.

use super::def::{Category, ProcessDef};

/// A CDP group heading plus the domain whose index page documents it. Domain is carried
/// because the browser navigates domain-first, and because two binaries (`fractal`, `repitch`)
/// legitimately appear in both.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CdpGroup {
    pub category: Category,
    pub name: &'static str,
}

/// Time-domain groups, in the order `cgroundx.htm` lists them.
pub const TIME_GROUPS: &[&str] = &[
    "DISTORT",
    "ENVEL",
    "EXTEND",
    "FILTER",
    "GRAIN",
    "HOUSEKEEP",
    "MODIFY",
    "MULTICHANNEL",
    "PSOW",
    "REPITCH",
    "REVERB",
    "SFEDIT",
    "SYNTH",
];

/// Spectral groups, in the order `cspecndx.htm` lists them.
pub const PVOC_GROUPS: &[&str] = &[
    "BLUR", "COMBINE", "FOCUS", "FORMANTS", "HILITE", "MORPH", "ONEFORM", "PITCH", "REPITCH",
    "SPEC", "SPECFNU", "SPECNU", "STRANGE", "STRETCH",
];

/// praatAudioTools groups — the plugin's own top-level directories, which is the same
/// principle the CDP tables follow: the heading reads as the tool's own material names it, so
/// someone reading the plugin's README finds the same bucket here.
///
/// Four are shortened because `CDP_GROUP_COL_WIDTH` gives a group name 13 usable columns (the
/// `praat_group_names_fit_the_browser_column` test enforces it), and the upstream directory
/// names run past that. The mapping from directory to heading is `PRAAT_DIRS`; only these four
/// differ from their directory verbatim:
///
/// | directory | heading |
/// |---|---|
/// | `Generative & Synthesis` | `Generative` |
/// | `Dynamics & Envelope` | `Dynamics` |
/// | `Spatial & Surround` | `Spatial` |
/// | `Time & Granular` | `Time/Granular` |
pub const PRAAT_GROUPS: &[&str] = &[
    "AI & Adaptive",
    "Analysis",
    "Distortion",
    "Dynamics",
    "Filter/Color",
    "Generative",
    "Modulation",
    "Pitch",
    "Reverb",
    "Spatial",
    "Spectral",
    "Time/Granular",
    "Vector Chain",
    "py",
];

/// Airwindows groups — Chris Johnson's own categories, taken verbatim from the registry
/// (`airwin2rack`'s `ModuleAdd.h`, itself derived from `Airwindopedia.txt`). Same principle as
/// the CDP and Praat tables: the heading reads as the suite's own material names it, so
/// someone reading the Airwindopedia finds the same bucket here.
///
/// Unlike `PRAAT_GROUPS` **none of these is shortened**, because none needs to be: the longest
/// is `Unclassified` at 12 characters against `CDP_GROUP_COL_WIDTH`'s 13 usable columns. So
/// there is no Airwindows counterpart to `PRAAT_DIRS` — the catalog's `bin` prefix and the
/// heading are the same string, and `every_airwindows_process_maps_to_a_group` is what catches
/// an upstream category that stops matching.
///
/// 23 groups, which with the `All` row above them is exactly `CDP_BROWSER_LIST_ROWS` (24). The
/// Groups column deliberately never scrolls, so a 24th category arriving upstream is a real
/// (if quiet) constraint — `airwindows_groups_fit_the_browser_list` fails rather than letting
/// a group become unreachable.
pub const AIRWINDOWS_GROUPS: &[&str] = &[
    "Ambience",
    "Amp Sims",
    "Bass",
    "Biquads",
    "Brightness",
    "Clipping",
    "Consoles",
    "Distortion",
    "Dithers",
    "Dynamics",
    "Effects",
    "Filter",
    "Lo-Fi",
    "Noise",
    "Reverb",
    "Saturation",
    "Stereo",
    "Subtlety",
    "Tape",
    "Tone Color",
    "Unclassified",
    "Utility",
    "XYZ Filters",
];

/// praatAudioTools directory → group heading. The directory is the leading path component of a
/// Praat entry's `bin` (e.g. `Distortion/Wavefolder__Foldback_.praat` → `Distortion`).
///
/// `Max-MSP` is deliberately absent: it holds a single Max/MSP helper rather than a sound
/// process, so listing it would leave an always-empty group.
///
/// `Vector Chain` *is* here. Its scripts chain sibling scripts located through
/// `preferencesDirectory$`, which `praat::runner::prepare_prefs_dir` satisfies by pointing
/// Praat at an app-owned preferences directory holding a `plugin_AudioTools` symlink — so they
/// run without anything being installed into the user's own Praat preferences folder.
///
/// `py` is here too, and keeps its directory name as its heading deliberately. Those scripts
/// write a temp WAV, shell out to a sibling Python helper, and read the result back — so alone
/// among the catalog they need something installed that this app does not ship: `numpy`,
/// `scipy` and `soundfile` on the interpreter Praat finds. A group of their own is what makes
/// that prerequisite visible in the browser rather than a surprise at run time, and lets anyone
/// who has not installed them ignore the lot in one place. Only the members whose Python halves
/// need nothing beyond those three are catalogued at all — the converter derives that per
/// script, so a helper that grows a `torch` import drops out with a reason rather than shipping
/// a process that cannot run.

const PRAAT_DIRS: &[(&str, &str)] = &[
    ("AI & Adaptive", "AI & Adaptive"),
    ("Analysis", "Analysis"),
    ("Distortion", "Distortion"),
    ("Dynamics & Envelope", "Dynamics"),
    ("Filter & Color", "Filter/Color"),
    ("Generative & Synthesis", "Generative"),
    ("Modulation", "Modulation"),
    ("Pitch", "Pitch"),
    ("Reverb", "Reverb"),
    ("Spatial & Surround", "Spatial"),
    ("Spectral", "Spectral"),
    ("Time & Granular", "Time/Granular"),
    ("Vector Chain", "Vector Chain"),
    ("py", "py"),
];

/// Time-domain `bin` → group. Most groups are named after their principal binary; the extra
/// entries are the smaller programs CDP documents *inside* that group's own page rather than
/// giving a heading of their own (e.g. everything in the `cdistort.htm` "OTHERS" section lands
/// in DISTORT, and `tremolo`/`tremenv` sit under ENVEL).
const TIME_BINS: &[(&str, &str)] = &[
    // DISTORT — the `distort` binary plus cdistort.htm's "OTHERS" section.
    ("distort", "DISTORT"),
    ("clip", "DISTORT"),
    ("distcut", "DISTORT"),
    ("distmark", "DISTORT"),
    ("distmore", "DISTORT"),
    ("distortt", "DISTORT"),
    ("distrep", "DISTORT"),
    ("distshift", "DISTORT"),
    ("frfractal", "DISTORT"),
    ("quirk", "DISTORT"),
    ("scramble", "DISTORT"),
    ("splinter", "DISTORT"),
    // ENVEL
    ("envel", "ENVEL"),
    ("flatten", "ENVEL"),
    ("spike", "ENVEL"),
    ("tremenv", "ENVEL"),
    ("tremolo", "ENVEL"),
    // EXTEND
    ("bounce", "EXTEND"),
    ("dvdwind", "EXTEND"),
    ("envspeak", "EXTEND"),
    ("extend", "EXTEND"),
    ("hover", "EXTEND"),
    ("hover2", "EXTEND"),
    ("motor", "EXTEND"),
    ("pulser", "EXTEND"),
    ("repeater", "EXTEND"),
    ("rotor", "EXTEND"),
    ("shifter", "EXTEND"),
    ("sorter", "EXTEND"),
    ("stutter", "EXTEND"),
    ("tesselate", "EXTEND"),
    // FILTER
    ("filter", "FILTER"),
    ("phasor", "FILTER"),
    // GRAIN
    ("grain", "GRAIN"),
    ("grainex", "GRAIN"),
    // HOUSEKEEP
    ("chanphase", "HOUSEKEEP"),
    ("gate", "HOUSEKEEP"),
    ("housekeep", "HOUSEKEEP"),
    ("repair", "HOUSEKEEP"),
    ("tostereo", "HOUSEKEEP"),
    // MODIFY
    ("modify", "MODIFY"),
    ("newdelay", "MODIFY"),
    ("phase", "MODIFY"),
    ("sfecho", "MODIFY"),
    ("verges", "MODIFY"),
    // MULTICHANNEL — CDP files these here. Until multichannel documents were first-class this
    // group held only the members whose *stereo* modes were usable; the `mch*` family and
    // `crumble`/`pairex` joined it once a document could actually hold and play their output.
    ("brownian", "MULTICHANNEL"),
    ("cascade", "MULTICHANNEL"),
    ("chirikov", "MULTICHANNEL"),
    ("crumble", "MULTICHANNEL"),
    ("crystal", "MULTICHANNEL"),
    ("mchanpan", "MULTICHANNEL"),
    ("mchanrev", "MULTICHANNEL"),
    ("mchiter", "MULTICHANNEL"),
    ("mchshred", "MULTICHANNEL"),
    ("mchzig", "MULTICHANNEL"),
    ("pairex", "MULTICHANNEL"),
    ("spin", "MULTICHANNEL"),
    ("strans", "MULTICHANNEL"),
    // PSOW
    ("psow", "PSOW"),
    ("tweet", "PSOW"),
    // REPITCH — the pitch-*curve* transforms. CDP documents REPITCH on its spectral page, but
    // these particular entries carry no audio at all (`IoKind::Curve`) and are `category = time`
    // here, so they surface under the time domain rather than being filed somewhere they would
    // never be found.
    ("repitch", "REPITCH"),
    // REVERB
    ("fastconv", "REVERB"),
    ("reverb", "REVERB"),
    ("rmverb", "REVERB"),
    ("tapdelay", "REVERB"),
    // SFEDIT
    ("cantor", "SFEDIT"),
    ("constrict", "SFEDIT"),
    ("packet", "SFEDIT"),
    ("prefix", "SFEDIT"),
    ("retime", "SFEDIT"),
    ("sfedit", "SFEDIT"),
    ("silend", "SFEDIT"),
    ("subtract", "SFEDIT"),
    ("topantail2", "SFEDIT"),
    ("waveform", "SFEDIT"),
    // SYNTH
    ("clicknew", "SYNTH"),
    ("impulse", "SYNTH"),
    ("multiosc", "SYNTH"),
    ("synfilt", "SYNTH"),
    ("synspline", "SYNTH"),
    ("synth", "SYNTH"),
];

/// Spectral `bin` → group, same convention as `TIME_BINS`.
const PVOC_BINS: &[(&str, &str)] = &[
    ("blur", "BLUR"),
    ("caltrain", "BLUR"),
    ("analjoin", "COMBINE"),
    ("combine", "COMBINE"),
    ("specsphinx", "COMBINE"),
    ("spectwin", "COMBINE"),
    ("focus", "FOCUS"),
    ("specfold", "FOCUS"),
    ("superaccu", "FOCUS"),
    ("formants", "FORMANTS"),
    ("glisten", "HILITE"),
    ("hilite", "HILITE"),
    ("morph", "MORPH"),
    ("oneform", "ONEFORM"),
    ("pitch", "PITCH"),
    ("repitch", "REPITCH"),
    ("spec", "SPEC"),
    ("specfnu", "SPECFNU"),
    ("matrix", "SPECNU"),
    ("selfsim", "SPECNU"),
    ("strange", "STRANGE"),
    ("spectstr", "STRETCH"),
    ("stretch", "STRETCH"),
];

/// The CDP group `def` belongs to, or `None` if its binary is not in the table — which is a
/// catalog/table disagreement rather than a real state, and is what
/// `every_catalog_process_maps_to_a_cdp_group` exists to prevent.
pub fn cdp_group(def: &ProcessDef) -> Option<CdpGroup> {
    // `fractal` is two unrelated programs sharing a name: `fractal wave` (time domain, filed
    // under DISTORT) and `fractal spectrum` (spectral, filed under SPECNU). The domain is what
    // tells them apart — there is no single answer keyed on the binary alone.
    // A Praat entry's group is its script's directory, not a binary name — there is only one
    // Praat binary and it tells you nothing about what the script does.
    if def.category == Category::Praat {
        let dir = def.bin.split('/').next()?;
        let name = PRAAT_DIRS.iter().find(|(d, _)| *d == dir).map(|(_, group)| *group)?;
        return Some(CdpGroup { category: def.category, name });
    }
    // An Airwindows entry's group is Chris Johnson's own category, carried in `bin`'s leading
    // component exactly as a Praat script's directory is (the catalog generator writes
    // `<Category>/<Name>`). Unlike Praat it needs no directory-to-heading mapping table: every
    // one of the 23 categories already fits the browser column, so the heading is the
    // category verbatim and `AIRWINDOWS_GROUPS` is the whole story.
    if def.category == Category::Airwindows {
        let cat = def.bin.split('/').next()?;
        let name = AIRWINDOWS_GROUPS.iter().find(|g| **g == cat).copied()?;
        return Some(CdpGroup { category: def.category, name });
    }
    let name = if def.bin == "fractal" {
        match def.category {
            Category::Time => "DISTORT",
            Category::Pvoc => "SPECNU",
            Category::Praat | Category::Airwindows => unreachable!("handled above"),
        }
    } else {
        let table = match def.category {
            Category::Time => TIME_BINS,
            Category::Pvoc => PVOC_BINS,
            Category::Praat | Category::Airwindows => unreachable!("handled above"),
        };
        table.iter().find(|(bin, _)| *bin == def.bin).map(|(_, group)| *group)?
    };
    Some(CdpGroup { category: def.category, name })
}

/// Every group defined for `category`, in CDP's own listing order.
pub fn groups_for(category: Category) -> &'static [&'static str] {
    match category {
        Category::Time => TIME_GROUPS,
        Category::Pvoc => PVOC_GROUPS,
        Category::Praat => PRAAT_GROUPS,
        Category::Airwindows => AIRWINDOWS_GROUPS,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::cdp::CdpCatalog;

    /// The table must cover the whole catalog. A process with no group would simply vanish from
    /// the browser's group filter — visible only under "All" — which is exactly the kind of
    /// silent omission that is hard to notice by hand across 400+ entries.
    #[test]
    fn every_catalog_process_maps_to_a_cdp_group() {
        let (catalog, _) = CdpCatalog::load(None);
        let missing: Vec<_> = catalog
            .processes
            .iter()
            .filter(|p| cdp_group(p).is_none())
            .map(|p| format!("{} (bin {}, {:?})", p.key, p.bin, p.category))
            .collect();
        assert!(missing.is_empty(), "processes with no CDP group: {missing:#?}");
    }

    /// Every group a process resolves to must be one the browser actually offers for that
    /// domain, or picking that group in the UI would show an empty list.
    #[test]
    fn every_resolved_group_is_listed_for_its_domain() {
        let (catalog, _) = CdpCatalog::load(None);
        for p in &catalog.processes {
            let group = cdp_group(p).expect("covered by every_catalog_process_maps_to_a_cdp_group");
            assert!(
                groups_for(group.category).contains(&group.name),
                "{} resolves to {} which is not listed for {:?}",
                p.key,
                group.name,
                group.category
            );
        }
    }

    /// The reverse direction: a listed group with nothing in it is a dead row in the UI. This
    /// catches a group surviving in the lists after every process using it was removed.
    #[test]
    fn every_listed_group_has_at_least_one_process() {
        let (catalog, _) = CdpCatalog::load(None);
        for category in [Category::Time, Category::Pvoc] {
            for name in groups_for(category) {
                let count = catalog
                    .processes
                    .iter()
                    .filter(|p| cdp_group(p) == Some(CdpGroup { category, name }))
                    .count();
                assert!(count > 0, "{name} ({category:?}) is listed but empty");
            }
        }
    }

    /// `fractal` is the one binary whose group genuinely depends on the domain; pin it so a
    /// future table edit can't collapse the two into one answer.
    #[test]
    fn fractal_resolves_differently_per_domain() {
        let (catalog, _) = CdpCatalog::load(None);
        for p in catalog.processes.iter().filter(|p| p.bin == "fractal") {
            let expected = match p.category {
                Category::Time => "DISTORT",
                Category::Pvoc => "SPECNU",
                Category::Praat | Category::Airwindows => {
                    unreachable!("no Praat or Airwindows entry has bin `fractal`")
                }
            };
            assert_eq!(cdp_group(p).unwrap().name, expected, "{}", p.key);
        }
    }
}
